config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/blog.rb
class Blog
  include Mongoid::Document
  include Mongoid::FullTextSearch

  field :title, type: String
  field :content, type: String
  field :views, type: Integer
  field :like, type: Integer

  fulltext_search_in :title, :content

  def self.search params
    if params[:search].present?
      # records = Blog.where(title: params[:search])
      records = Blog.any_of({:title => params[:search]}, {:content => params[:search]})
    else
      # records = Blog.page(params[:page])
      records = Blog.limit(100)
    end
    records
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document

  belongs_to :post
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :body, type: String

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::FullTextSearch

  has_many :comments
  field :title, type: String
  field :content, type: String
  field :body, type: String
  field :views, type: Integer
  field :like, type: Integer

  fulltext_search_in :title, :content

  def self.search params
    if params[:search].present?
      records = Post.any_of({:title => params[:search]}, {:body => params[:search]})
    else
      records = Post.limit(100)
    end
    records
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /Comments
  # GET /Comments.json
  def index
    @comments = @post.comments
  end

  # GET /Comments/1
  # GET /Comments/1.json
  def show
  end

  # GET /Comments/new
  def new
    @comment = Comment.new
  end

  # GET /Comments/1/edit
  def edit
  end

  # Comment /Comments
  # Comment /Comments.json
  def create
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Comments/1
  # PATCH/PUT /Comments/1.json
  def update
    respond_to do |format|
      if @comment.update_attributes!(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Comments/1
  # DELETE /Comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:first_name, :last_name, :email, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # (1..200000).each do |i|
    #   Post.find_or_create_by(title: "Post Title #{i}", body: "Post Content #{i}")
    # end
    @query = Post.search(params)
    @total_count = @query.count
    @posts = @query
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, url: post_comment_path(@post, @comment.id)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "Email Address", required: true %>
  </div>

  <div class="form-group">
    <%= f.label 'Message' %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", post_path(@post), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<!-- <%#= link_to 'Show', @post %> | -->
<%#= link_to 'Back', posts_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts (<%=@total_count%>)</h1>
<div class="well">
  <%= form_for posts_path, html: {method: :get, class: 'form-inline', style: 'display: inline-block;'} do |f| %>
    <div class="form-group">
      <%= text_field_tag "search", params[:search], class: "form-control" %>
    </div>
    <%= f.submit("Search", class: "btn btn-primary") %>
  <% end %>
  <%= link_to "New Post", new_post_path, class: "btn btn-primary pull-right" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/comments/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%#= link_to 'Back', posts_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @post.title %></h1>

<p>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<hr>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="pull-right">
      <td><%= link_to 'Edit', edit_post_comment_path(@post, comment.id) %></td>
      <td><%= link_to 'Destroy', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </div>
    <h3 class="panel-title"><%=comment.name%></h3>
  </div>
  <div class="panel-body"><%=comment.body%></div>
</div>
<% end%>

<br>

<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "Email Address", required: true %>
  </div>

  <div class="form-group">
    <%= f.label 'Message' %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails with Mongodb | Lalit Kumar Maurya</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", posts_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<!-- <%#= link_to 'Show', @post %> | -->
<%#= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts (<%=@total_count%>)</h1>
<div class="well">
  <%= form_for posts_path, html: {method: :get, class: 'form-inline', style: 'display: inline-block;'} do |f| %>
    <div class="form-group">
      <%= text_field_tag "search", params[:search], class: "form-control" %>
    </div>
    <%= f.submit("Search", class: "btn btn-primary") %>
  <% end %>
  <%= link_to "New Post", new_post_path, class: "btn btn-primary pull-right" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%#= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<hr>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="pull-right">
      <td><%= link_to 'Edit', edit_post_comment_path(@post, comment.id) %></td>
      <td><%= link_to 'Destroy', post_comment_path(@post, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </div>
    <h3 class="panel-title"><%=comment.name%></h3>
  </div>
  <div class="panel-body"><%=comment.body%></div>
</div>
<% end%>

<br>

<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "Email Address", required: true %>
  </div>

  <div class="form-group">
    <%= f.label 'Message' %>
    <%= f.text_area :body, class: "form-control", required: true %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>